server:
  port: 8080
spring:
  ##数据库连接信息
  datasource:
    # 数据源配置
    url: jdbc:mysql://192.168.1.129:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # SQLException: XAER_INVAL: Invalid arguments (or unsupported command)问题
    xa:
      properties:
        pinGlobalTxToPhysicalConnection: true
        useServerPrepStmts: true
  activiti:
    # 自动建表
    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true
  security:
    user:
      name: admin
      password: admin
